= Spring Cloud GCP SQL Ejemplo

Este proyecto es un ejemplo de como conectar spring-boot con cloud sql en un ambiente standard de appengine 

Es necesario una base de datos segunda generación google cloud.
appengine google cloud standard java 8.
glcoud skd con los componentes de java instalados.

== Setup

1. Para agregar la compatibilidad con appengine standard se siguieron las siguientes instrucciones  https://github.com/GoogleCloudPlatform/getting-started-java/tree/master/appengine-standard-java8/springboot-appengine-standard

2. Para hacer una conexión con jdbc se reutilizó el código del siguiente repositorio https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-sql-sample
resumen: Crea una base de datos de usuarios y agrega valores al arrancar la aplicación con los archivos. 
schema.sql y data.sql
ir a para probar http://localhost:8080/getTuples


3. Para hacer la conexión con spring data se reutilizó el siguiente repositorio https://github.com/spring-cloud/spring-cloud-gcp/tree/master/spring-cloud-gcp-samples/spring-cloud-gcp-data-jpa-sample
resumen: Al arrancar la aplicación crea una tabla en la base de datos a la cual le agrega un registro
probar en http://localhost:8080/getHouses


4. Open the link:src/main/resources/application.properties[application.properties] file and replace
*[database-name]* with the name of the database you created in step 3 and
*[instance-connection-name]* with the instance connection name of the instance you created in
step 1.
+
Configuraciones previas 

1. Dar permisos de conexión al proyecto
en el siguiente enlace https://console.cloud.google.com/iam-admin/iam
Selecciona tu projecto
luego en la sección de IAM busca la cuenta default
similar a your-project-id@appspot.gserviceaccount.com
clic en icono de editar
en función agregar Cloud SQL -> Cliente SQL
Ahora la cuenta debería tener permisos para hacer operaciones a la base de datos.

2 Activar la api de google cloud sql 

3 Descargar las credenciales
en el siguiente enlace https://console.cloud.google.com/apis/credentials/serviceaccountkey
seleccionar App Engine default service account 
crear credenciales y descargar json
sustituir las credenciales descargadas en el archivo src/main/resources/keys-gcp.json

4 agregar las propiedades de GAE

en el archivo application.properties, completar todas las propiedades vacías con los valores de la instancia y proyecto de google cloud

spring.cloud.gcp.sql.database-name=
spring.cloud.gcp.sql.instance-connection-name=
spring.datasource.username=
spring.datasource.password=
spring.cloud.gcp.project-id=

con esto será posible correr en localhost 

mvn install
mvn appengine:run


+
Desplegar en appengine

asegurate de estar  logueado con una cuenta que tenga permisos del projecto
gcloud auth login

En el archivo pom.xml en la línea 76 en configuration project pegar el id del proyecto al cual desplegará


== 

usar como arquetipo 

borrar directorios  com/example/ -> jdbc y jpa
borrar los archivos de resources/  sql data.sql y schema.sql

opcional ->refactorizar el nombre del paquete com.example
con esto se tiene un proyecto limpio